defaults: &defaults
  working_directory: ~/grafana-kentik-app
  docker:
    - image: circleci/node:10.9.0-jessie

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@6.4.0'
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - run: npm audit fix
      - run:
          name: Grafana core dependencies
          command: git clone https://github.com/grafana/grafana.git --no-checkout --depth 1 grafana-master
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - grafana-master
      - run: npm run-script build
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install

workflows:
  version: 2
  build-test:
    jobs:
      - build
      #- test:
      #    requires:
      #      - build
